name = "tux-robot"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-06-04"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CONVERSATION_HISTORY"
id = "7c147881ce7d42b8811bfbf8c38e3ee4"

[[r2_buckets]]
binding = "R2"
bucket_name = "share"

[[queues.producers]]
binding = "MESSAGE_QUEUE"
queue = "tux-robot-messages"

[[queues.consumers]]
queue = "tux-robot-messages"
max_batch_size = 10
max_batch_timeout = 5

[sandbox]
binding = "Sandbox"

[env.dev]
name = "tux-robot-dev"

[env.dev.ai]
binding = "AI"

[[env.dev.kv_namespaces]]
binding = "CONVERSATION_HISTORY"
id = "7c147881ce7d42b8811bfbf8c38e3ee4"

[[env.dev.r2_buckets]]
binding = "R2"
bucket_name = "share"

[[env.dev.queues.producers]]
binding = "MESSAGE_QUEUE"
queue = "tux-robot-messages-dev"

[[env.dev.queues.consumers]]
queue = "tux-robot-messages-dev"
max_batch_size = 10
max_batch_timeout = 5

[env.dev.sandbox]
binding = "Sandbox"

[env.production]
name = "tux-robot"

[env.production.ai]
binding = "AI"

[[env.production.kv_namespaces]]
binding = "CONVERSATION_HISTORY"
id = "7c147881ce7d42b8811bfbf8c38e3ee4"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "share"

[[env.production.queues.producers]]
binding = "MESSAGE_QUEUE"
queue = "tux-robot-messages"

[[env.production.queues.consumers]]
queue = "tux-robot-messages"
max_batch_size = 10
max_batch_timeout = 5

[env.production.sandbox]
binding = "Sandbox"
