name = "tux-robot"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-06-04"

[vars]
ENVIRONMENT = "production"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "tux-robot-knowledge"

[[kv_namespaces]]
binding = "CONVERSATION_HISTORY"
id = "7c147881ce7d42b8811bfbf8c38e3ee4"

[[r2_buckets]]
binding = "R2"
bucket_name = "share"

[[containers]]
class_name = "Sandbox"
image = "docker.io/cloudflare/sandbox:0.10.1-python"

[[durable_objects.bindings]]
class_name = "Sandbox"
name = "Sandbox"

[[migrations]]
new_sqlite_classes = ["Sandbox"]
tag = "v1"

[[workflows]]
name = "bot-workflow"
binding = "STREAM_WORKFLOW"
class_name = "BotWorkflow"

[env.dev]
name = "tux-robot-dev"

[env.dev.vars]
ENVIRONMENT = "dev"

[env.dev.ai]
binding = "AI"

[[env.dev.vectorize]]
binding = "VECTORIZE"
index_name = "tux-robot-knowledge-dev"

[[env.dev.kv_namespaces]]
binding = "CONVERSATION_HISTORY"
id = "7c147881ce7d42b8811bfbf8c38e3ee4"

[[env.dev.r2_buckets]]
binding = "R2"
bucket_name = "share"

[[env.dev.workflows]]
name = "bot-workflow-dev"
binding = "STREAM_WORKFLOW"
class_name = "BotWorkflow"

[[env.dev.containers]]
class_name = "Sandbox"
image = "docker.io/cloudflare/sandbox:0.10.1-python"

[[env.dev.durable_objects.bindings]]
class_name = "Sandbox"
name = "Sandbox"

[env.production]
name = "tux-robot"

[env.production.vars]
ENVIRONMENT = "production"

[env.production.ai]
binding = "AI"

[[env.production.vectorize]]
binding = "VECTORIZE"
index_name = "tux-robot-knowledge"

[[env.production.kv_namespaces]]
binding = "CONVERSATION_HISTORY"
id = "7c147881ce7d42b8811bfbf8c38e3ee4"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "share"

[[env.production.workflows]]
name = "bot-workflow"
binding = "STREAM_WORKFLOW"
class_name = "BotWorkflow"

[[env.production.containers]]
class_name = "Sandbox"
image = "docker.io/cloudflare/sandbox:0.10.1-python"

[[env.production.durable_objects.bindings]]
class_name = "Sandbox"
name = "Sandbox"
